In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 82.8 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.29 s


In [10]:
import numpy as np

In [11]:
data = np.random.randn(2, 3)

In [13]:
data

array([[ 0.74626997,  0.19169191,  0.81146447],
       [-0.27768663, -1.10447304, -0.64450444]])

In [14]:
data*10

array([[  7.46269969,   1.91691909,   8.11464474],
       [ -2.77686629, -11.0447304 ,  -6.44504443]])

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
data1 = [6, 7.5, 8, 0, 1]

In [18]:
arr1 = np.array(data1)

In [19]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])